# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d54327ff70534f34b6fe9d2a11d6accc535a49b09d2a7245802b2f8476ac40936b00f4510a6f8540fc86f921cac236cc286e62a62c34151059413ccd17b83d9

test:
  secret_key_base: 338d6529211f0efdbac6a4791331b92c58a3e11b8c61180545a3e60a4b8e7efcfea85199d2b66edc56c49777b73ee2f7a40d7bb77827dad206d5d7692b531976

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
